Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -109,6 +109,13 @@ jobs:
           xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u DamiPPV.py || echo "DamiPPV failed"
           sync
 
+      - name: Run DamiStreams Scraper
+        continue-on-error: true
+        run: |
+          curl -L -f -o DamiStreams.py "${{ secrets.DAMI_STREAMED_URL }}"
+          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u DamiStreams.py || echo "DamiStreams failed"
+          sync
+
       - name: Run RawGit Scraper
         continue-on-error: true
         run: |
@@ -126,9 +133,8 @@ jobs:
           curl -L -s -o channels.txt "https://tinyurl.com/4ze5nm6p"
           curl -L -f -k --connect-timeout 15 "https://www.dropbox.com/scl/fi/a1ux3ha4kwn5pb895jj5s/Mediauu.m3u?rlkey=z688agdc3h5o8312j00fwe4qx&st=th1tmh3k&dl=1" -o "dropbox_mediauu.m3u" -s
 
-          # Added freeproxy.m3u and streamedProxy.m3u8 to the source list for merging
-          for f in "Pits.m3u8" "xyzProxied.m3u8" "DamiPPV_vlc.m3u8" "roxProxied.m3u" "SGo.m3u" "playlist.m3u8" "ddhd.m3u8" "Bite.m3u8" "Bite247.m3u8" "DamiPPVProxy_vlc.m3u8" "PitsProxied.m3u8" "Bite_MatchDay.m3u8" "rox.m3u" "xyz.m3u8" "spx.m3u"; do
-          #for f in "PitsProxied.m3u8" "xyzProxied.m3u8" "DamiPPVProxy_vlc.m3u8" "SGo.m3u" "roxProxied.m3u" "playlist.m3u8" "ddhd.m3u8" "Bite.m3u8" "Bite247.m3u8" "Bite_MatchDay.m3u8" "spx.m3u"; do
+          # Added freeproxy.m3u, streamedProxy.m3u8, DamiStreams.m3u8 and DamiStreamsProxied.m3u8 to the source list for merging
+          for f in "Pits.m3u8" "xyzProxied.m3u8" "DamiPPV_vlc.m3u8" "roxProxied.m3u" "SGo.m3u" "playlist.m3u8" "ddhd.m3u8" "Bite.m3u8" "Bite247.m3u8" "DamiStreams.m3u8" "DamiPPVProxy_vlc.m3u8" "PitsProxied.m3u8" "Bite_MatchDay.m3u8" "rox.m3u" "xyz.m3u8" "spx.m3u" "DamiStreamsProxied.m3u8" ; do
             if [ -s "$f" ]; then
               echo -e "\n######## SOURCE: ${f%.*} ########" >> "$OUTPUT_FILE"
               sed 's/\r$//' "$f" | grep -v '^#EXTM3U' >> "$OUTPUT_FILE"
