Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -57,6 +57,15 @@ jobs:
           xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u pits.py || echo "⚠️ pits failed..."
           sync
 
+      - name: Run MovieBite Scraper
+        shell: bash
+        continue-on-error: true
+        run: |
+          echo "--- Running MovieBite Scraper ---"
+          curl -L -f -o movbyte.py "${{ secrets.MOVEBITE_URL }}"
+          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u movbyte.py || echo "⚠️ MovieBite failed..."
+          sync
+
       - name: Run DamiPPV Scraper
         shell: bash
         continue-on-error: true
@@ -126,7 +135,7 @@ jobs:
           curl -L -s -o channels.txt "https://tinyurl.com/4ze5nm6p"
           
           # Merge local M3U files in priority order
-          for f in "pits_vlc.m3u8" "DamiPPV_vlc.m3u8" "StreamedCDN.m3u" "rox.m3u" "RawGit.m3u" "spx.m3u" "SSpo99.m3u8" "SS99_Events.m3u8"; do
+          for f in "pits_vlc.m3u8" "playlist.m3u8" "DamiPPV_vlc.m3u8" "rox.m3u" "RawGit.m3u" "spx.m3u" "SSpo99.m3u8" "SS99_Events.m3u8" "StreamedCDN.m3u"; do
             if [ -s "$f" ]; then
               echo -e "\n######## SOURCE: ${f%.*} ########" >> "$OUTPUT_FILE"
               sed 's/\r$//' "$f" | grep -v '^#EXTM3U' >> "$OUTPUT_FILE"
