Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,6 +47,15 @@ jobs:
           playwright install firefox chrome chromium
           playwright install-deps firefox chrome chromium
 
+      - name: Run NinjaSGO Scraper
+        shell: bash
+        continue-on-error: true
+        run: |
+          echo "--- Running NinjaSGO Scraper ---"
+          curl -L -f -o ninjasgo.py "${{ secrets.NINJASGO_URL }}"
+          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u ninjasgo.py || echo "⚠️ NinjaSGO failed..."
+          sync
+
       - name: Run ROX Scraper
         shell: bash
         continue-on-error: true
@@ -121,11 +130,10 @@ jobs:
           echo "#EXTM3U url-tvg=\"${EPG_URL}\"" > "$OUTPUT_FILE"
 
           curl -L -s -o channels.txt "https://tinyurl.com/4ze5nm6p"
-          
           curl -L -f -k --connect-timeout 15 "https://www.dropbox.com/scl/fi/a1ux3ha4kwn5pb895jj5s/Mediauu.m3u?rlkey=z688agdc3h5o8312j00fwe4qx&st=th1tmh3k&dl=1" -o "dropbox_mediauu.m3u" -s
 
-          # Merging files including the new STplaylist.m3u
-          for f in "rox.m3u" "DamiPPV_vlc.m3u8" "pits_vlc.m3u8" "spx.m3u" "playlist.m3u8" "channels.m3u" "dropbox_mediauu.m3u" "RawGit.m3u"; do
+          # Merging files - SGo.m3u added to the front of the loop
+          for f in "SGo.m3u" "rox.m3u" "DamiPPV_vlc.m3u8" "pits_vlc.m3u8" "spx.m3u" "playlist.m3u8" "channels.m3u" "dropbox_mediauu.m3u" "RawGit.m3u"; do
             if [ -s "$f" ]; then
               echo -e "\n######## SOURCE: ${f%.*} ########" >> "$OUTPUT_FILE"
               sed 's/\r$//' "$f" | grep -v '^#EXTM3U' >> "$OUTPUT_FILE"
