Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,6 +44,13 @@ jobs:
           playwright install firefox chromium
           playwright install-deps firefox chromium
 
+      - name: Run Hoofoot Scraper
+        continue-on-error: true
+        run: |
+          curl -L -f -o hoofoot.py "${{ secrets.HOOFOOT_URL }}"
+          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u hoofoot.py || echo "Hoofoot failed"
+          sync
+
       - name: Run DamiPopular Scraper
         continue-on-error: true
         run: |
@@ -191,7 +198,7 @@ jobs:
           fi
 
           # Loop through existing structured local outputs (using our dynamically resolved playlist variable)
-          for f in "xyz.m3u8" "Pits.m3u8" "$TML_PLAYLIST" "Daddy247.m3u8" "SSpo99.m3u8" "SportsBiteChannels.m3u8" "Damiplaylist.m3u" "DamiPopular.m3u8" "BiteEvents.m3u8" "SS99_Events.m3u8" "DamiPPV_vlc.m3u8" "rox.m3u" "zlive.m3u8" "asaraaaaaaao.m3u8" "spx.m3u" "playlist.m3u8" "ddhd.m3u8" "dropbox_mediauu.m3u" "RawGit333.m3u"; do
+          for f in "xyz.m3u8" "Pits.m3u8" "hoofoot_playlist.m3u" "$TML_PLAYLIST" "Daddy247.m3u8" "SSpo99.m3u8" "SportsBiteChannels.m3u8" "Damiplaylist.m3u" "DamiPopular.m3u8" "BiteEvents.m3u8" "SS99_Events.m3u8" "DamiPPV_vlc.m3u8" "rox.m3u" "zlive.m3u8" "asaraaaaaaao.m3u8" "spx.m3u" "playlist.m3u8" "ddhd.m3u8" "dropbox_mediauu.m3u" "RawGit333.m3u"; do
             if [ -s "$f" ]; then
               echo -e "\n######## SOURCE: ${f%.*} ########" >> "$OUTPUT_FILE"
               sed 's/\r$//' "$f" | grep -v '^#EXTM3U' >> "$OUTPUT_FILE"
