Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,6 +45,15 @@ jobs:
           xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u TMLMAIN.py || echo "⚠️ TMLMAIN failed..."
           sync
 
+      - name: Run DamiTV Scraper
+        shell: bash
+        continue-on-error: true
+        run: |
+          echo "--- Running DamiTV Scraper ---"
+          curl -L -f -o DamiTV.py "${{ secrets.DAMI_URL }}"
+          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u DamiTV.py || echo "⚠️ DamiTV failed..."
+          sync
+
       - name: Run PitSport Scraper
         shell: bash
         continue-on-error: true
@@ -111,8 +120,8 @@ jobs:
 
           curl -L -s -o channels.txt "https://tinyurl.com/4ze5nm6p"
           
-          # 1. Local Scraper Files Order
-          for f in "tms1.m3u" "pitspt.m3u" "rox.m3u" "SSpo99.m3u8" "SS99_Events.m3u8" "spx.m3u"; do
+          # 1. Local Scraper Files Order (Added DamiTV.m3u)
+          for f in "tms1.m3u" "DamiTV.m3u" "pitspt.m3u" "rox.m3u" "SSpo99.m3u8" "SS99_Events.m3u8" "spx.m3u"; do
             if [ -s "$f" ]; then
               echo -e "\n######## SOURCE: ${f%.*} ########" >> "$OUTPUT_FILE"
               sed 's/\r$//' "$f" | grep -v '^#EXTM3U' >> "$OUTPUT_FILE"
@@ -156,6 +165,16 @@ jobs:
           DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
           source_path: MyStuffCLW.m3u
           dest_path: /MyStuff/MyStuffCLW.m3u
+
+      - name: Upload DamiTV Backup
+        if: hashFiles('DamiTV.m3u') != ''
+        uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
+        with:
+          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
+          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
+          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
+          source_path: DamiTV.m3u
+          dest_path: /MyStuff/DamiTV.m3u
 
       - name: Upload TML Backup
         if: hashFiles('tms1.m3u') != ''
