Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -81,6 +81,13 @@ jobs:
           xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u movbyte.py || echo "MovByte failed"
           sync
 
+      - name: Run MovBiteChannels Scraper
+        continue-on-error: true
+        run: |
+          curl -L -f -o movbite_channels.py "${{ secrets.MOVBITECHANNELS_URL }}"
+          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u movbite_channels.py || echo "MovBiteChannels failed"
+          sync
+
       - name: Run DamiChannels Scraper
         continue-on-error: true
         run: |
@@ -126,8 +133,8 @@ jobs:
           curl -L -s -o channels.txt "https://tinyurl.com/4ze5nm6p"
           curl -L -f -k --connect-timeout 15 "https://www.dropbox.com/scl/fi/a1ux3ha4kwn5pb895jj5s/Mediauu.m3u?rlkey=z688agdc3h5o8312j00fwe4qx&st=th1tmh3k&dl=1" -o "dropbox_mediauu.m3u" -s
 
-          # Added pits_raw.m3u8 alongside pits_vlc.m3u8
-          for f in "pits_vlc.m3u8" "pits_raw.m3u8" "XYZplaylist.m3u" "SGo.m3u" "rox.m3u" "DamiPPV_vlc.m3u8" "spx.m3u" "playlist.m3u8" "channels.m3u" "dropbox_mediauu.m3u" "RawGit.m3u" "resolved_channels.m3u" "DChannels.m3u"; do
+          # Added Bite.m3u8 and SBS.m3u8 to the list for merging
+          for f in "Bite.m3u8" "SBS.m3u8" "pits_vlc.m3u8" "pits_raw.m3u8" "XYZplaylist.m3u" "SGo.m3u" "rox.m3u" "DamiPPV_vlc.m3u8" "spx.m3u" "playlist.m3u8" "channels.m3u" "dropbox_mediauu.m3u" "RawGit.m3u" "resolved_channels.m3u" "DChannels.m3u"; do
             if [ -s "$f" ]; then
               echo -e "\n######## SOURCE: ${f%.*} ########" >> "$OUTPUT_FILE"
               sed 's/\r$//' "$f" | grep -v '^#EXTM3U' >> "$OUTPUT_FILE"
