Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -54,8 +54,8 @@ jobs:
       - name: Run XYZ Scraper
         continue-on-error: true
         run: |
-          curl -L -f -o XYZ.py "${{ secrets.XYZ_URL }}"
-          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u XYZ.py || echo "XYZ failed"
+          curl -L -f -o xyz.py "${{ secrets.XYZ_URL }}"
+          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u xyz.py || echo "XYZ failed"
           sync
 
       - name: Run ROX Scraper
@@ -123,6 +123,22 @@ jobs:
           xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u RawGit_Scraper.py || echo "RawGit failed"
           sync
 
+      - name: Run SS99 Events Scraper
+        continue-on-error: true
+        run: |
+          rm -rf ss99events/* && mkdir -p ss99events
+          curl -L -f -o ss99_events.py "${{ secrets.SS99_EVENTS_URL }}"
+          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u ss99_events.py || echo "SS99 Events failed"
+          sync
+
+      - name: Run SS99 Channels Scraper
+        continue-on-error: true
+        run: |
+          rm -rf ss99channels/* && mkdir -p ss99channels
+          curl -L -f -o ss99_channels.py "${{ secrets.SS99_CHANNELS_URL }}"
+          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u ss99_channels.py || echo "SS99 Channels failed"
+          sync
+
       - name: Process and Merge All Playlists
         run: |
           set +e 
@@ -154,7 +170,7 @@ jobs:
           curl -L -f -k -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --connect-timeout 15 "https://www.dropbox.com/scl/fi/k4iafut5kmys261ms3951/asarao.m3u8?rlkey=ovcvg7zqydoivrw4vanub9su4&st=me5y4i2h&dl=1" -o "asarao.m3u8" -s
 
           # DO NOT TOUCH THIS OR MOVE IT ANYWHERE, LEAVE IT AS IT IS -----  "DamiPPVProxy_vlc.m3u8" "PitsProxied.m3u8" "Bite_MatchDay.m3u8" "DamiStreamsProxied.m3u8" "xyzProxied.m3u8" "roxProxied.m3u"
-          for f in "tms1.m3u" "Pits.m3u8" "rox.m3u" "xyz.m3u8" "spx.m3u" "DamiPPV_vlc.m3u8" "SGo.m3u" "playlist.m3u8" "ddhd.m3u8" "Bite.m3u8" "Bite247.m3u8" "dropbox_mediauu.m3u" "asarao.m3u8" "DamiStreams.m3u8"; do
+          for f in "tms1.m3u" "Pits.m3u8" "rox.m3u" "xyz.m3u8" "spx.m3u" "DamiPPV_vlc.m3u8" "SGo.m3u" "playlist.m3u8" "ddhd.m3u8" "Bite.m3u8" "Bite247.m3u8" "dropbox_mediauu.m3u" "asarao.m3u8" "DamiStreams.m3u8" "SS99_Events.m3u8" "SSpo99.m3u8"; do
             if [ -s "$f" ]; then
               echo -e "\n######## SOURCE: ${f%.*} ########" >> "$OUTPUT_FILE"
               sed 's/\r$//' "$f" | grep -v '^#EXTM3U' >> "$OUTPUT_FILE"
@@ -198,7 +214,7 @@ jobs:
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git add ptsp/
+          git add ptsp/ ss99events/ ss99channels/
           if ! git diff-index --quiet HEAD --; then
             git commit -m "Update Scraper Data: $(date +'%Y-%m-%d %H:%M')"
             git pull --rebase origin main
