Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,6 +44,13 @@ jobs:
           playwright install firefox
           playwright install-deps firefox
 
+      - name: Run TMLMain Scraper
+        continue-on-error: true
+        run: |
+          curl -L -f -o TMLMain.py "${{ secrets.TMLMAIN_URL }}"
+          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u TMLMain.py || echo "TMLMain failed"
+          sync
+
       - name: Run XYZ Scraper
         continue-on-error: true
         run: |
@@ -119,7 +126,8 @@ jobs:
           curl -L -s -o channels.txt "https://tinyurl.com/4ze5nm6p"
           curl -L -f -k --connect-timeout 15 "https://www.dropbox.com/scl/fi/a1ux3ha4kwn5pb895jj5s/Mediauu.m3u?rlkey=z688agdc3h5o8312j00fwe4qx&st=th1tmh3k&dl=1" -o "dropbox_mediauu.m3u" -s
 
-          for f in "pits_vlc.m3u8" "XYZplaylist.m3u" "SGo.m3u" "rox.m3u" "DamiPPV_vlc.m3u8" "spx.m3u" "playlist.m3u8" "channels.m3u" "dropbox_mediauu.m3u" "RawGit.m3u"; do
+          # Added tms1.m3u as the first source in the loop
+          for f in "tms1.m3u" "pits_vlc.m3u8" "XYZplaylist.m3u" "SGo.m3u" "rox.m3u" "DamiPPV_vlc.m3u8" "spx.m3u" "playlist.m3u8" "channels.m3u" "dropbox_mediauu.m3u" "RawGit.m3u"; do
             if [ -s "$f" ]; then
               echo -e "\n######## SOURCE: ${f%.*} ########" >> "$OUTPUT_FILE"
               sed 's/\r$//' "$f" | grep -v '^#EXTM3U' >> "$OUTPUT_FILE"
