Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -95,18 +95,11 @@ jobs:
           xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u dami_daddybite.py || echo "DamiDaddyBite failed"
           sync
 
-      - name: Run DamiChannels Scraper
+      - name: Run StreamedSU Proxy Scraper
         continue-on-error: true
         run: |
-          curl -L -f -o dami_channels.py "${{ secrets.DAMICHANNELS_URL }}"
-          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u dami_channels.py || echo "DamiC failed"
-          sync
-
-      - name: Run DamiChannels Resolved Scraper
-        continue-on-error: true
-        run: |
-          curl -L -f -o dami_channels_resolved.py "${{ secrets.DAMICHANNELS_RESOLVED_URL }}"
-          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u dami_channels_resolved.py || echo "DamiC Resolved failed"
+          curl -L -f -o streamed_proxy.py "${{ secrets.STREAMED_URL }}"
+          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u streamed_proxy.py || echo "StreamedSU Scraper failed"
           sync
 
       - name: Run SPX Scraper
@@ -140,8 +133,8 @@ jobs:
           curl -L -s -o channels.txt "https://tinyurl.com/4ze5nm6p"
           curl -L -f -k --connect-timeout 15 "https://www.dropbox.com/scl/fi/a1ux3ha4kwn5pb895jj5s/Mediauu.m3u?rlkey=z688agdc3h5o8312j00fwe4qx&st=th1tmh3k&dl=1" -o "dropbox_mediauu.m3u" -s
 
-          # Added freeproxy.m3u to the source list for merging
-          for f in "pits_vlc.m3u8" "pits_raw.m3u8" "XYZplaylist.m3u" "SGo.m3u" "rox.m3u" "playlist.m3u8" "ddhd.m3u8" "Bite.m3u8" "Bite247.m3u8" "DamiPPV_vlc.m3u8" "Bite_MatchDay.m3u8" "spx.m3u"; do
+          # Added freeproxy.m3u and streamedProxy.m3u8 to the source list for merging
+          for f in "pits_vlc.m3u8" "pits_raw.m3u8" "XYZplaylist.m3u" "SGo.m3u" "rox.m3u" "playlist.m3u8" "ddhd.m3u8" "Bite.m3u8" "Bite247.m3u8" "DamiPPV_vlc.m3u8" "Bite_MatchDay.m3u8" "spx.m3u" "streamedProxy.m3u8"; do
             if [ -s "$f" ]; then
               echo -e "\n######## SOURCE: ${f%.*} ########" >> "$OUTPUT_FILE"
               sed 's/\r$//' "$f" | grep -v '^#EXTM3U' >> "$OUTPUT_FILE"
