Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -57,6 +57,15 @@ jobs:
           xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u TMLMAIN.py || echo "⚠️ TMLMAIN failed..."
           sync
 
+      - name: Run DAMISTREAMED Scraper
+        shell: bash
+        continue-on-error: true
+        run: |
+          echo "--- Running DAMISTREAMED Scraper ---"
+          curl -L -f -o DAMISTREAMED.py "${{ secrets.DAMISTREAMED_URL }}"
+          python3 -u DAMISTREAMED.py || echo "⚠️ DAMISTREAMED failed..."
+          sync
+
       - name: Run DAMI Scraper
         shell: bash
         continue-on-error: true
@@ -154,7 +163,8 @@ jobs:
           curl -L -s -o channels.txt "https://tinyurl.com/4ze5nm6p"
           
           # Merge local M3U files in priority order
-          for f in "tms1.m3u"  "rox.m3u" "str_final.m3u" "DAMiltered.m3u" "StreamedCDN.m3u" "RawGit.m3u" "pitspt.m3u" "spx.m3u" "SSpo99.m3u8" "SS99_Events.m3u8" "PPVss.m3u"; do
+          # Added str.m3u8 after tms1.m3u
+          for f in "tms1.m3u" "str.m3u8" "rox.m3u" "str_final.m3u" "DAMiltered.m3u" "StreamedCDN.m3u" "RawGit.m3u" "pitspt.m3u" "spx.m3u" "SSpo99.m3u8" "SS99_Events.m3u8" "PPVss.m3u"; do
             if [ -s "$f" ]; then
               echo -e "\n######## SOURCE: ${f%.*} ########" >> "$OUTPUT_FILE"
               sed 's/\r$//' "$f" | grep -v '^#EXTM3U' >> "$OUTPUT_FILE"
@@ -201,6 +211,16 @@ jobs:
           source_path: MyPlayList.m3u
           dest_path: /MyStuff/MyPlayList.m3u
 
+      - name: Upload DAMISTREAMED (str.m3u8) to Dropbox
+        if: hashFiles('str.m3u8') != ''
+        uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
+        with:
+          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
+          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
+          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
+          source_path: str.m3u8
+          dest_path: /MyStuff/str.m3u8
+
       - name: Upload DamiCDN to Dropbox
         if: hashFiles('StreamedCDN.m3u') != ''
         uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
@@ -211,10 +231,10 @@ jobs:
           source_path: StreamedCDN.m3u
           dest_path: /MyStuff/StreamedCDN.m3u
 
-      - name: Upload Backup Files to Dropbox
+      - name: Upload Backup Files to Dropbox (Logging)
         if: always()
         run: |
-          files=("PPVss.m3u" "DAMiltered.m3u" "tms1.m3u" "pitspt.m3u" "rox.m3u" "str_final.m3u" "SSpo99.m3u8" "SS99_Events.m3u8" "spx.m3u" "RawGit.m3u")
+          files=("PPVss.m3u" "str.m3u8" "DAMiltered.m3u" "tms1.m3u" "pitspt.m3u" "rox.m3u" "str_final.m3u" "SSpo99.m3u8" "SS99_Events.m3u8" "spx.m3u" "RawGit.m3u")
           for f in "${files[@]}"; do
             if [ -f "$f" ]; then
               echo "Uploading $f to Dropbox..."
