Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,8 +48,7 @@ jobs:
           apt-get install -y python3-pip python3-full curl xvfb git
           python3 -m pip install httpx[http2] aiohttp dropbox requests pycryptodome python-dateutil tqdm beautifulsoup4 playwright --break-system-packages
           playwright install firefox chromium
-          playwright install chrome
-        shell: bash
+          shell: bash
 
       - name: Run PTSPT Scraper
         continue-on-error: true
@@ -97,6 +96,15 @@ jobs:
           sync
         shell: bash
 
+      - name: Run PPL Scraper
+        continue-on-error: true
+        run: |
+          echo "--- Running PPL Scraper ---"
+          echo "${{ secrets.PPL_SCRIPT }}" > ppl_script.py
+          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u ppl_script.py || echo "⚠️ PPL failed..."
+          sync
+        shell: bash
+
       - name: Process and Merge All Playlists
         run: |
           set +e 
@@ -109,7 +117,7 @@ jobs:
           echo "------------------------------------------------" >> "$REPORT_FILE"
           
           echo -e "\n--- Processing Scraped Local Files ---"
-          for f in "pitspt.m3u" "tms1.m3u" "spx.m3u" "SSpo99.m3u8" "SS99_Events.m3u8" "S4.m3u8" "rftv.m3u"; do
+          for f in "pitspt.m3u" "tms1.m3u" "spx.m3u" "pcx.m3u" "SSpo99.m3u8" "SS99_Events.m3u8" "S4.m3u8" "rftv.m3u"; do
             if [ -s "$f" ]; then
               SIZE=$(du -h "$f" | cut -f1)
               echo "✅ [SUCCESS] $f ($SIZE) - Merging..."
@@ -163,6 +171,16 @@ jobs:
           DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
           source_path: MyStuffCLW.m3u
           dest_path: /MyStuff/MyStuffCLW.m3u
+
+      - name: Upload Standalone PCX to Dropbox
+        if: hashFiles('pcx.m3u') != ''
+        uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
+        with:
+          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
+          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
+          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
+          source_path: pcx.m3u
+          dest_path: /MyStuff/pcx.m3u
 
       - name: Upload Standalone PTSPT to Dropbox
         if: hashFiles('pitspt.m3u') != ''
