Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,11 +44,11 @@ jobs:
           playwright install firefox chromium
           playwright install-deps firefox chromium
 
-      - name: Run TMLMAIN Scraper
+      - name: Run DamiPopular Scraper
         continue-on-error: true
         run: |
-          curl -L -f -o tmlmain.py "${{ secrets.TMLMAIN_URL }}"
-          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u tmlmain.py || echo "TMLMAIN failed"
+          curl -L -f -o DamiPopular.py "${{ secrets.DAMI_POPULAR_URL }}"
+          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u DamiPopular.py || echo "DamiPopular failed"
           sync
 
       - name: Run XYZ Scraper
@@ -109,13 +109,6 @@ jobs:
           xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u DamiPPV.py || echo "DamiPPV failed"
           sync
 
-      - name: Run DamiStreams Scraper
-        continue-on-error: true
-        run: |
-          curl -L -f -o DamiStreams.py "${{ secrets.DAMI_STREAMED_URL }}"
-          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" python3 -u DamiStreams.py || echo "DamiStreams failed"
-          sync
-
       - name: Run RawGit Scraper
         continue-on-error: true
         run: |
@@ -169,7 +162,7 @@ jobs:
           curl -L -f -k -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" --connect-timeout 15 "https://www.dropbox.com/scl/fi/k4iafut5kmys261ms3951/asarao.m3u8?rlkey=ovcvg7zqydoivrw4vanub9su4&st=me5y4i2h&dl=1" -o "asarao.m3u8" -s
 
           # Loop through existing structured local outputs
-          for f in "tms1.m3u" "Pits.m3u8" "rox.m3u" "xyz.m3u8" "SS99_Events.m3u8" "SSpo99.m3u8" "Daddy247.m3u8" "BiteEvents.m3u8" "spx.m3u" "DamiPPV_vlc.m3u8" "SGo.m3u" "playlist.m3u8" "ddhd.m3u8" "Bite.m3u8" "dropbox_mediauu.m3u" "asarao.m3u8" "DamiStreams.m3u8"; do
+          for f in "DamiPopular.m3u8" "tms1.m3u" "Pits.m3u8" "rox.m3u" "xyz.m3u8" "SS99_Events.m3u8" "SSpo99.m3u8" "Daddy247.m3u8" "BiteEvents.m3u8" "spx.m3u" "DamiPPV_vlc.m3u8" "SGo.m3u" "playlist.m3u8" "ddhd.m3u8" "Bite.m3u8" "dropbox_mediauu.m3u" "asarao.m3u8"; do
             if [ -s "$f" ]; then
               echo -e "\n######## SOURCE: ${f%.*} ########" >> "$OUTPUT_FILE"
               sed 's/\r$//' "$f" | grep -v '^#EXTM3U' >> "$OUTPUT_FILE"
